import Head from "next/head";
import { Inter } from "next/font/google";
import "tailwindcss/tailwind.css";
import { useSelector, useDispatch } from "react-redux";
import { openLoginModal } from "@/redux/modalSlice";
import LoginModal from "@/components/modals/LoginModal";

import Footer from "@/components/Footer";
import Features from "@/components/Features";
import Reviews from "@/components/Reviews";
import LandingNavBar from "@/components/LandingNavBar";
import Landing from "@/components/Landing";
import Numbers from "@/components/Numbers";

export default function Home() {
  // Use in future
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Summarist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="./globals.css" />
      </Head>

        {/* Have route to next pages? */}
        <LandingNavBar />
        <Landing />
        <Features />
        <Reviews />
        <Numbers />
        <Footer />
    </>
  );
}
